version: "3.1"
services:
    www:
        build: ./docker/php
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/php/www:/var/www/html/
            - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/log/apache2:/var/log/apache2
            - ./docker/php/log/cron:/var/log/cron
        links:
            - db
        networks:
            - default
    netdata:
        image: netdata/netdata
        container_name: netdata
        hostname: localhost # set to fqdn of host
        ports:
            - 19999:19999
        restart: unless-stopped
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - netdatalib:/var/lib/netdata
            - netdatacache:/var/cache/netdata
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /etc/os-release:/host/etc/os-release:ro
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:
    netdatalib:
    netdatacache:
